#!/usr/bin/expect -f

puts "\n\n"
system "figlet -d /home/cmiranda/.local/share/figlet -f \"ANSI Shadow\" -c 'CCA' | lolcat"
puts ""

puts "🐧 Requesting sudo password..."
set sudopass [exec /home/cmiranda/bin/1p sudo-password]

puts "🌎 Requesting VPN credentials..."
set username [exec /home/cmiranda/bin/1p cca-vpn-username]
set password [exec /home/cmiranda/bin/1p cca-vpn-password]

puts "🫣 Writing credentials to file..."
set outputFilename "/tmp/vpn_credentials.txt"
set outFileId [open $outputFilename "w"]
puts -nonewline $outFileId "$username\n"
puts -nonewline $outFileId "$password\n"
close $outFileId

puts "🔑 Requesting OTP..."
set otp [exec /home/cmiranda/bin/1p cca-vpn-otp]
# expect_user -re "(.*)\n"
# set otp $expect_out(1,string)

spawn sudo openvpn --daemon --config /home/cmiranda/.config/openvpn/profiles/cca.ovpn --auth-user-pass /tmp/vpn_credentials.txt
expect "password for cmiranda:"
send "$sudopass\r"
expect "CHALLENGE: Enter Authenticator Code"
send "$otp\r"

puts "\n🛜 Connecting to VPN..."

sleep 5
puts "🗑 Removing credentials file..."
system "rm $outputFilename"

# Hand over control to user
interact
