#!/usr/bin/expect -f

proc clearAndDisplayTitle {} {
    system "clear"
    puts ""
    system "figlet -d /home/cmiranda/.local/share/figlet -f \"ANSI Shadow\" -c 'VPN' | lolcat"
}

clearAndDisplayTitle
puts "🐧 Requesting sudo password..."
set sudopass [exec /home/cmiranda/bin/1p sudo-password]

clearAndDisplayTitle
puts "🌎 Requesting VPN credentials..."
set username [exec /home/cmiranda/bin/1p cca-vpn-username]
set password [exec /home/cmiranda/bin/1p cca-vpn-password]

clearAndDisplayTitle
puts "🫣 Writing credentials to file..."
set outputFilename "/tmp/vpn_credentials.txt"
set outFileId [open $outputFilename "w"]
puts -nonewline $outFileId "$username\n"
puts -nonewline $outFileId "$password\n"
close $outFileId

clearAndDisplayTitle
puts "🔑 Requesting OTP..."
set otp [exec /home/cmiranda/bin/1p cca-vpn-otp]

spawn sudo openvpn --daemon --config /home/cmiranda/.config/openvpn/profiles/cca.ovpn --auth-user-pass /tmp/vpn_credentials.txt
expect "password for cmiranda:"
send "$sudopass\r"
expect "Enter Authenticator Code"
send "$otp\r"

clearAndDisplayTitle
puts "🛜 Connecting to VPN..."

sleep 5
clearAndDisplayTitle
puts "🗑 Removing credentials file..."
system "rm $outputFilename"

# Hand over control to user
interact
