#!/usr/bin/expect -f

puts "\n\n"
system "figlet -d /home/cmiranda/.local/share/figlet -f \"ANSI Shadow\" -c 'HOME' | lolcat"
puts ""

puts "🐧 Requesting sudo password..."
set sudopass [exec /home/cmiranda/bin/1p sudo-password]

puts "\n🛜 Connecting to VPN..."
spawn sudo openvpn --daemon --config /home/cmiranda/.config/openvpn/profiles/home.ovpn
expect "password for cmiranda:"
send "$sudopass\r"

# Hand over control to user
interact
