#!/usr/bin/expect -f

puts "\n\n"
system "figlet -d /home/cmiranda/.local/share/figlet -f \"ANSI Shadow\" -c 'LG' | lolcat"
puts ""

puts "🔑 YubiKey OTP:"
stty -echo
expect_user -re "(.*)\n"
stty echo
set yubi $expect_out(1,string)

puts "🐧 Requesting sudo password..."
set sudopass [exec /home/cmiranda/bin/1p sudo-password]

puts "🌎 Requesting VPN credentials..."
set username [exec /home/cmiranda/bin/1p lg-vpn-username]
set password [exec /home/cmiranda/bin/1p lg-vpn-password]

puts "🫣 Writing credentials to file..."
set outputFilename "/tmp/vpn_credentials.txt"
set outFileId [open $outputFilename "w"]
puts -nonewline $outFileId "$username\n"
puts -nonewline $outFileId "$password"
puts -nonewline $outFileId "$yubi\n"
close $outFileId

spawn sudo openvpn --daemon --config /home/cmiranda/.config/openvpn/profiles/lg.ovpn --auth-user-pass /tmp/vpn_credentials.txt
expect "password for cmiranda:"
send "$sudopass\r"

puts ""
puts "🛜 Connecting to VPN..."

sleep 5
puts "🗑 Removing credentials file..."
system "rm $outputFilename"

# Hand over control to user
interact
