#!/usr/bin/expect -f

set server [lindex $argv 0];

puts "🛜 Connecting to $server..."

set timeout 2
spawn sshc $server
expect {
    "*assword: " {
        set timeout 10
        puts ""
        puts "🔑 YubiKey OTP:"
        stty -echo
        expect_user -re "(.*)\n"
        stty echo
        set yubi $expect_out(1,string)

        puts "🐧 Requesting sudo password..."
        set sudopass [exec /home/cmiranda/bin/1p sudo-password]

        puts "🌎 Requesting LDAP credentials..."
        set username [exec /home/cmiranda/bin/1p lg-ldap-username]
        set password [exec /home/cmiranda/bin/1p lg-ldap-password]

        send "${password}${yubi}\r"

        # Hand over control to user
        interact

        # After user is done, exit
        exit
    }
}

# Hand over control to user
interact
