version: '3.3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer-dotfiles
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9082:9000
      - 9083:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

#  watchtower:
#    image: v2tec/watchtower
#    container_name: watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ${HOME}/.docker/config.json:/config.json
#    command: --label-enable --cleanup --schedule "0 4 * * *"

