#!/bin/bash

case "$1" in
    --toggle)
        muted=`dunstctl is-paused 2> /dev/null`
        if [[ $muted == "true" ]]; then
            dunstctl set-paused false 2> /dev/null
        else
            dunstctl set-paused true 2> /dev/null
        fi
        ;;
    *)
        muted=`dunstctl is-paused 2> /dev/null`
        if [[ $muted == "true" ]]; then
            echo "🤐"
        else
            echo "🔔"
        fi
        ;;
esac
