#!/bin/bash

ACTIVE_COLOR="#E0B42F"
INACTIVE_COLOR="#858585"

case "$1" in
--toggle)
    muted=$(dunstctl is-paused 2>/dev/null)
    if [[ $muted == "true" ]]; then
        dunstctl set-paused false 2>/dev/null
    else
        dunstctl set-paused true 2>/dev/null
    fi
    ;;
*)
    muted=$(dunstctl is-paused 2>/dev/null)
    if [[ $muted == "true" ]]; then
        echo "%{T3}%{F${INACTIVE_COLOR}}󰂛%{F-}%{T-}"
    else
        echo "%{T3}%{F${ACTIVE_COLOR}}󰂞%{F-}%{T-}"
    fi
    ;;
esac
