#!/bin/bash

ARCH_BLUE_COLOR=`$HOME/bin/theme -k blue`
ARCH_RED_COLOR=`$HOME/bin/theme -k red`

# Check if the Broadlink LED Strip is on or off
if [ -f /tmp/broadlink-led-strip.status ]; then
    STATUS=$(cat /tmp/broadlink-led-strip.status)
else
    STATUS="off"
fi

if [ "$STATUS" = "off" ]; then
        COLOR=$ARCH_BLUE_COLOR
    else
        COLOR=$ARCH_RED_COLOR
    fi

echo " %{T4}%{F$COLOR}%{F-}%{T-}"
