#!/bin/bash

MUTED_COLOR="#FF6961"
UNMUTED_COLOR="#8BC34A"

RUNNING_DEVICE=$(pactl list short sources | awk '/RUNNING/ {print $2}')
MUTED="$(pactl list short sources | awk '/input.*RUNNING/ {system("pactl get-source-mute " $1)}' | sed 's/Mute: //g' | uniq)"

if [[ $RUNNING_DEVICE =~ "HD_Pro_Webcam" ]]; then
    DEVICE_ICON="󰖠"
elif [[ $RUNNING_DEVICE =~ "CalDigit" ]]; then
    DEVICE_ICON="󱂩"
elif [[ $RUNNING_DEVICE =~ "HiFi__hw_sof" ]]; then
    DEVICE_ICON=""
elif [[ $RUNNING_DEVICE =~ "bluez" ]]; then
    DEVICE_ICON="󰋋"
elif [[ $RUNNING_DEVICE =~ "analog" ]]; then
    DEVICE_ICON=""
elif [[ $RUNNING_DEVICE =~ "USB_Audio" ]]; then
    DEVICE_ICON="󰓃"
fi

if [[ $MUTED == "no" ]]; then
    echo "%{F${UNMUTED_COLOR}}$DEVICE_ICON%{F-}"
else
    echo "%{F${MUTED_COLOR}}$DEVICE_ICON%{F-}"
fi
