#!/bin/bash

MIC="`amixer get Capture | grep % | sed -r 's/.*%\]\s\[(.*)\]/\1/' | sed -n 1p`"
if [[ $MIC == "on" ]]; then
    brightnessctl --device='platform::micmute' set 0 > /dev/null
    echo "%{F#20c418}%{F-}"
else
    brightnessctl --device='platform::micmute' set 1 > /dev/null
    echo "%{F#f53636}%{F-}"
fi
