#!/bin/sh

(
    # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 10 seconds
    flock -w 10 200 || exit 1

    if ! updates_arch=$(checkupdates 2>/dev/null | wc -l); then
        updates_arch=0
    fi

    if ! updates_aur=$(yay -Qum 2>/dev/null | wc -l); then
        updates_aur=0
    fi

    updates=$((updates_arch + updates_aur))

    if [ "$updates" -gt 0 ]; then
        echo "📦 $updates "
    else
        echo ""
    fi

) 200>/tmp/.polybar-packages.exclusivelock
