#!/bin/bash

AUR_COLOR="#03A9F4"
PACMAN_COLOR="#E0B42F"
KERNEL_COLOR="#FF6961"
AUR_AND_PACMAN_COLOR="#8BC34A"

(
    # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 10 seconds
    flock -w 10 200 || exit 1

    ping -q -c1 google.com &>/dev/null || (echo "" && exit 1)

    packages_to_be_updated=$(checkupdates | awk '{print $1}')
    kernel_packages_to_be_updated_count=$(echo -e "$packages_to_be_updated" | grep -P '^(linux|linux-headers|linux-lts|linux-lts-headers)$' | wc -l)

    if ! updates_arch=$(echo -e "$packages_to_be_updated" | grep -v '^$' | wc -l); then
        updates_arch=0
    fi

    if ! updates_aur=$(yay -Qum 2>/dev/null | wc -l); then
        updates_aur=0
    fi

    # Pick color depending on source of updates
    if [ "$updates_arch" -gt 0 ] && [ "$updates_aur" -gt 0 ]; then
        color=$AUR_AND_PACMAN_COLOR
    elif [ "$updates_arch" -gt 0 ]; then
        color=$PACMAN_COLOR
    elif [ "$updates_aur" -gt 0 ]; then
        color=$AUR_COLOR
    fi

    # Always show kernel updates color
    if [ "$kernel_packages_to_be_updated_count" -gt 0 ]; then
        color=$KERNEL_COLOR
    fi

    icon="󰏔"
    updates=$((updates_arch + updates_aur))
    if [ "$updates" -gt 0 ]; then
        echo "%{F$color}%{T3}$icon%{T-} $updates%{F-}"
    else
        echo ""
    fi

) 200>/tmp/.polybar-packages.exclusivelock
