#!/bin/bash

status=$(playerctl -p spotify status 2> /dev/null)

if [ "$status" == "Playing" ]; then
	echo ""
	polybar-msg action "#spotify.module_show" 2> /dev/null
else
	polybar-msg action "#spotify.module_hide" 2> /dev/null
fi

