#!/bin/bash

unread_count=$(find /home/$USER/.thunderbird -name 'INBOX.msf' -exec grep -REo 'A1=[0-9]' {} + | tac | head -n 1 | awk -F '=' '{print $2}')

if [[ -z "$unread_count" || "$unread_count" -eq 0 ]]; then
  echo ""
else
  echo "%{F#FFFFFF}✉%{F-} $unread_count"
fi
