#!/bin/bash

# get lines, reverse to keep first instances of each account
lines=$(find /home/$USER/.thunderbird -name 'INBOX.msf' -exec grep --text -REo 'A1=[0-9]' {} + | tac)

# store account names
accounts=()

# store sum of unread count
unread_count=0

# loop through lines
while read -r line; do
  account=$(echo $line | grep -o '.*/ImapMail/[^/]*/INBOX.msf')
  # if account not in accounts array, add it and add the count to the total
  if [[ ! " ${accounts[@]} " =~ " ${account} " ]]; then
    accounts+=("$account")
    count=$(echo $line | grep -o 'A1=[0-9]' | awk -F '=' '{print $2}')
    ((unread_count += count))
  fi
done <<<"$lines"

if [[ -z "$unread_count" || "$unread_count" -eq 0 ]]; then
  echo ""
else
  echo "%{T3}%{F#FFFFFF}󰇮%{T-}%{F-}"
fi
