#!/bin/bash

(
    # Wait for lock on /var/lock/.myscript.exclusivelock (fd 200) for 5 seconds
    flock -w 5 200 || exit 1

    UPS_STATUS=$(apcaccess status)

    VOLTAGE_IN=$(echo "$UPS_STATUS" | grep LINEV | awk '{print $3}' | xargs printf "%.0fV")

    echo $VOLTAGE_IN
) 200>/tmp/.polybar-ups.exclusivelock
