#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)
docked=$(cat /proc/acpi/button/lid/LID/state | grep closed | wc -l)

if [ "$capacity" -ge 75 ]; then
	icon=""
	color="#0cc078"
elif [ "$capacity" -ge 50 ]; then
	icon=""
	color="#79de79"
elif [ "$capacity" -ge 25 ]; then
	icon=""
	color="#fcfc99"
else
	icon=""
	color="#fb6962"
fi

[ -z $warn ] && warn=" "

if [[ "$status" = "Charging" || "$status" = "Unknown" || "$status" = "Full" ]]; then
	icon=""
	color="#ffffff"
fi

if [[ $docked == 1 ]]; then
	icon=""
	color="#ffffff"
fi

echo "$icon $capacity"%
echo "$icon $capacity"%
echo $color
