#!/bin/bash

case "$BLOCK_BUTTON" in
    1)
        muted=`dunstctl is-paused`
        if [[ $muted == "true" ]]; then
            dunstctl set-paused false
        else
            dunstctl set-paused true
        fi
    ;;
esac

muted=`dunstctl is-paused`
if [[ $muted == "true" ]]; then
    echo "🤐"
else
    echo "🔔"
fi