#!/bin/bash

case $BLOCK_BUTTON in
    1)
        firefox-developer-edition https://github.com/notifications
        i3-msg '[class="firefoxdeveloperedition$"] focus' > /dev/null
    ;;
esac

GITHUB_TOKEN=`$HOME/bin/reveal-secret github.notifications.token`

notifications_count=`curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/notifications | grep '"unread": true' | wc -l`

if [[ "$notifications_count" -eq "0" ]]; then
    echo ""
else
    echo "<span size='x-large'></span>"
fi

exit 0
