#!/bin/bash

case "$BLOCK_BUTTON" in
    1)
        pamac-manager --updates
    ;;
esac

aur_count=$(yay -Qu | wc -l)
arch_count=$(checkupdates | wc -l)

packages_count=$(expr $aur_count + $arch_count)

[[ "${packages_count}" = "0" ]] && exit 0

echo "📦 $packages_count"
exit 0
