#!/bin/bash

case "$BLOCK_BUTTON" in
    1)
        pamac-manager --updates
    ;;
esac

packages_count=$(checkupdates | wc -l)
[[ "${packages_count}" = "0" ]] && exit 0

echo "📦 $packages_count"
exit 0
