#!/bin/sh

case $BLOCK_BUTTON in
    3)
        ~/bin/radio off
    ;;
esac

CURRENT_RADIO_STATION_FILE=/tmp/current-radio-station

if test -f "$CURRENT_RADIO_STATION_FILE"; then
	current_station=$(cat $CURRENT_RADIO_STATION_FILE)
	echo "📻 <span>$current_station</span>"
else
	exit 0
fi
