swipe:
  3:
    begin:
      command: xdotool mousedown 1
    update:
      command: xdotool mousemove_relative -- $move_x, $move_y
      interval: 0.01
      accel: 2
    end:
      command: xdotool mouseup 1
  4: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key ctrl+shift+plus'
    down: 
      command: 'xdotool key ctrl+minus'
#  3:
#    left:
#      command: "xdotool key super+alt+Left" # Switch to next workspace
#    right:
#      command: "xdotool key super+alt+Right" # Switch to previous workspace
#    down:
#      command: "xdotool key ctrl+r"
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.7
  pinch: 0.2

interval:
  swipe: 1
  pinch: 1
