version: '3.3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9082:9000
      - 9083:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_PATH}/portainer:/data

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    ports:
      - 8200:8200
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUMES_PATH}/duplicati/config:/config
      - ${VOLUMES_PATH}/duplicati/backups:/backups
      - /:/source
