[colors.primary]
background = "#1E1E2E" # base
foreground = "#CDD6F4" # text
dim_foreground = "#CDD6F4" # text
bright_foreground = "#CDD6F4" # text

[colors.cursor]
text = "#1E1E2E" # base
cursor = "#F5E0DC" # rosewater

[colors.vi_mode_cursor]
text = "#1E1E2E" # base
cursor = "#B4BEFE" # lavender

[colors.search.matches]
foreground = "#1E1E2E" # base
background = "#A6ADC8" # subtext0

[colors.search.focused_match]
foreground = "#1E1E2E" # base
background = "#A6E3A1" # green

[colors.footer_bar]
foreground = "#1E1E2E" # base
background = "#A6ADC8" # subtext0

[colors.hints.start]
foreground = "#1E1E2E" # base
background = "#F9E2AF" # yellow

[colors.hints.end]
foreground = "#1E1E2E" # base
background = "#A6ADC8" # subtext0

[colors.selection]
text = "#1E1E2E" # base
background = "#F5E0DC" # rosewater

[colors.normal]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1

[colors.bright]
black = "#585B70" # surface2
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#A6ADC8" # subtext0

[colors.dim]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"
