name: Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create docker container
      run: docker-compose up -d dots
    - name: Sync submodules
      run: docker exec dots bash -c "git -C /home/cmiranda/dotfiles submodule sync --recursive && git submodule update --init --recursive /home/cmiranda/dotfiles"
    - name: Run dotbot sync
      run: docker exec dots bash -c "HOSTNAME=Linux-MBP /home/cmiranda/dotfiles/scripts/sync.sh"
